package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

var (
	cdfPattern       = regexp.MustCompile(`CDF(\d+)\(([^)]*)\)`)
	designatedScalar = regexp.MustCompile(`\[(\w+)\s*\]\s*=\s*([A-Z0-9_]+|\d+)`)
	designatedRow    = regexp.MustCompile(`\[(\w+)\s*\]\s*=\s*\{\s*([^}]*)\}`)
	scanArrayPattern = regexp.MustCompile(`static const uint16_t ALIGN\((scan_[0-9x]+)\[\], 32\) = \{([^}]*)\};`)
)

func main() {
	if len(os.Args) != 3 {
		fatalf("usage: gendav1dtables <dav1d-src-dir> <output-go-file>")
	}
	srcDir := os.Args[1]
	outPath := os.Args[2]

	cdfText := readFile(filepath.Join(srcDir, "cdf.c"))
	tablesText := readFile(filepath.Join(srcDir, "tables.c"))
	dequantText := readFile(filepath.Join(srcDir, "dequant_tables.c"))
	scanText := readFile(filepath.Join(srcDir, "scan.c"))

	var buf bytes.Buffer
	fmt.Fprintln(&buf, "// Code generated by internal/cmd/gendav1dtables; DO NOT EDIT.")
	fmt.Fprintln(&buf, "package decoder")
	fmt.Fprintln(&buf)

	writePartitionCDF(&buf, cdfText)
	write2DCDFArray(&buf, cdfText, ".skip = {", ".skip_mode = {", "generatedSkipCDF", 3, 2)
	write2DCDFArray(&buf, cdfText, ".skip_mode = {", ".partition = {", "generatedSkipModeCDF", 3, 2)
	write2DCDFArray(&buf, cdfText, ".intra = {", ".comp = {", "generatedIntraCDF", 4, 2)
	write2DCDFArray(&buf, cdfText, ".newmv_mode = {", ".globalmv_mode = {", "generatedNewMVModeCDF", 6, 2)
	write2DCDFArray(&buf, cdfText, ".globalmv_mode = {", ".refmv_mode = {", "generatedGlobalMVModeCDF", 2, 2)
	write2DCDFArray(&buf, cdfText, ".refmv_mode = {", ".drl_bit = {", "generatedRefMVModeCDF", 6, 2)
	write2DCDFArray(&buf, cdfText, ".drl_bit = {", ".comp_inter_mode = {", "generatedDRLBitCDF", 3, 2)
	write2DCDFArray(&buf, cdfText, ".comp_inter_mode = {", ".intra = {", "generatedCompInterModeCDF", 8, 8)
	write3DCDFArray(&buf, cdfText, ".ref = {", ".comp_fwd_ref = {", "generatedRefCDF", 6, 3, 2)
	write2DCDFArray(&buf, cdfText, ".comp = {", ".comp_dir = {", "generatedCompCDF", 5, 2)
	write2DCDFArray(&buf, cdfText, ".comp_dir = {", ".jnt_comp = {", "generatedCompDirCDF", 5, 2)
	write2DCDFArray(&buf, cdfText, ".jnt_comp = {", ".mask_comp = {", "generatedJntCompCDF", 6, 2)
	write2DCDFArray(&buf, cdfText, ".mask_comp = {", ".wedge_comp = {", "generatedMaskCompCDF", 6, 2)
	write2DCDFArray(&buf, cdfText, ".wedge_comp = {", ".wedge_idx = {", "generatedWedgeCompCDF", 9, 2)
	write2DCDFArray(&buf, cdfText, ".wedge_idx = {", ".interintra = {", "generatedWedgeIdxCDF", 9, 16)
	write2DCDFArray(&buf, cdfText, ".interintra = {", ".interintra_mode = {", "generatedInterIntraCDF", 4, 2)
	write2DCDFArray(&buf, cdfText, ".interintra_mode = {", ".interintra_wedge = {", "generatedInterIntraModeCDF", 4, 4)
	write2DCDFArray(&buf, cdfText, ".interintra_wedge = {", ".ref = {", "generatedInterIntraWedgeCDF", 7, 2)
	write3DCDFArray(&buf, cdfText, ".comp_fwd_ref = {", ".comp_bwd_ref = {", "generatedCompFwdRefCDF", 3, 3, 2)
	write3DCDFArray(&buf, cdfText, ".comp_bwd_ref = {", ".comp_uni_ref = {", "generatedCompBwdRefCDF", 2, 3, 2)
	write3DCDFArray(&buf, cdfText, ".comp_uni_ref = {", ".txsz = {", "generatedCompUniRefCDF", 3, 3, 2)
	writeSingleCDF(&buf, cdfText, ".intrabc = {", "generatedIntraBCCDF", 2)
	write2DCDFArray(&buf, cdfText, ".y_mode = {", ".use_filter_intra = {", "generatedYModeCDF", 4, 13)
	writeUseFilterIntra(&buf, cdfText)
	writeSingleCDF(&buf, cdfText, ".filter_intra = {", "generatedFilterIntraCDF", 5)
	write3DCDFArray(&buf, cdfText, ".pal_y = {", ".pal_sz = {", "generatedPalYCDF", 7, 3, 2)
	write3DCDFArray(&buf, cdfText, ".pal_sz = {", ".pal_uv = {", "generatedPalSizeCDF", 2, 7, 8)
	write2DCDFArray(&buf, cdfText, ".pal_uv = {", ".color_map = {", "generatedPalUVCDF", 2, 2)
	write4DCDFArray(&buf, cdfText, ".color_map = {", ".intrabc = {", "generatedColorMapCDF", 2, 7, 5, 8)
	writeUVModeCDF(&buf, cdfText)
	write2DCDFArray(&buf, cdfText, ".angle_delta = {", ".filter = {", "generatedAngleDeltaCDF", 8, 7)
	writeKFYModeCDF(&buf, cdfText)
	write3DCDFArray(&buf, cdfText, ".txsz = {", ".txpart = {", "generatedTXSizeCDF", 4, 3, 4)
	write3DCDFArray(&buf, cdfText, ".txpart = {", ".txtp_inter1 = {", "generatedTXPartCDF", 7, 3, 2)
	write2DCDFArray(&buf, cdfText, ".txtp_inter1 = {", ".txtp_inter2 = {", "generatedTXTypeInter1CDF", 2, 16)
	writeSingleCDF(&buf, cdfText, ".txtp_inter2 = {", "generatedTXTypeInter2CDF", 12)
	write2DCDFArray(&buf, cdfText, ".txtp_inter3 = {", ".txtp_intra1 = {", "generatedTXTypeInter3CDF", 4, 2)
	write3DCDFArray(&buf, cdfText, ".txtp_intra1 = {", ".txtp_intra2 = {", "generatedTXTypeIntra1CDF", 2, 13, 7)
	write3DCDFArray(&buf, cdfText, ".txtp_intra2 = {", ".skip = {", "generatedTXTypeIntra2CDF", 3, 13, 5)
	writeCoefCDFTables(&buf, cdfText)
	writeMVCDFTables(&buf, cdfText)

	writeScalarTable(&buf, tablesText, "dav1d_ymode_size_context", blockSizeNames, "generatedYModeSizeContext")
	writeScalarTable(&buf, tablesText, "dav1d_intra_mode_context", intraLumaModeNames, "generatedIntraModeContext")
	writeRowTable(&buf, tablesText, "dav1d_max_txfm_size_for_bs", blockSizeNames, 4, "generatedMaxTXSizeForBlock")
	writeScalarTable(&buf, tablesText, "dav1d_txtp_from_uvmode", uvModeNames, "generatedTXTypeFromUVMode")
	writeFlatScalarListTable(&buf, tablesText, "dav1d_tx_types_per_set", 40, "generatedTXTypesPerSet")
	writeFlatScalarListTable(&buf, tablesText, "dav1d_filter_mode_to_y_mode", 5, "generatedFilterModeToYMode")
	writeDequantTable(&buf, dequantText)
	writeScanTables(&buf, scanText)

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fatalf("format generated source: %v\n%s", err, buf.String())
	}
	if err := os.WriteFile(outPath, formatted, 0o644); err != nil {
		fatalf("write output: %v", err)
	}
}

func writePartitionCDF(buf *bytes.Buffer, cdfText string) {
	block := extractBlock(cdfText, ".partition = {")
	matches := cdfPattern.FindAllStringSubmatch(block, -1)
	if len(matches) != 20 {
		fatalf("partition cdf count = %d, want 20", len(matches))
	}
	fmt.Fprintln(buf, "var generatedPartitionCDF = [numBlockLevels][4][10]uint16{")
	idx := 0
	for level := 0; level < 5; level++ {
		fmt.Fprintln(buf, "{")
		for ctx := 0; ctx < 4; ctx++ {
			vals := parseCDFValues(matches[idx][2])
			idx++
			fmt.Fprintf(buf, "%s,\n", formatUint16Array(vals, 10))
		}
		fmt.Fprintln(buf, "},")
	}
	fmt.Fprintln(buf, "}")
	fmt.Fprintln(buf)
}

func write2DCDFArray(buf *bytes.Buffer, cdfText, marker, nextMarker, name string, rows, size int) {
	block := extractSection(cdfText, marker, nextMarker)
	matches := cdfPattern.FindAllStringSubmatch(block, -1)
	if len(matches) != rows {
		fatalf("%s cdf count = %d, want %d", name, len(matches), rows)
	}
	fmt.Fprintf(buf, "var %s = [%d][%d]uint16{\n", name, rows, size)
	for _, m := range matches {
		vals := parseCDFValues(m[2])
		fmt.Fprintf(buf, "%s,\n", formatUint16Array(vals, size))
	}
	fmt.Fprintln(buf, "}")
	fmt.Fprintln(buf)
}

func writeSingleCDF(buf *bytes.Buffer, cdfText, marker, name string, size int) {
	block := extractBlock(cdfText, marker)
	match := cdfPattern.FindStringSubmatch(block)
	if len(match) != 3 {
		fatalf("%s: cdf not found", name)
	}
	vals := parseCDFValues(match[2])
	fmt.Fprintf(buf, "var %s = %s\n\n", name, formatUint16Array(vals, size))
}

func writeUseFilterIntra(buf *bytes.Buffer, cdfText string) {
	block := extractSection(cdfText, ".use_filter_intra = {", ".filter_intra = {")
	rows := designatedRow.FindAllStringSubmatch(block, -1)
	values := make([][]uint16, len(blockSizeNames))
	for _, row := range rows {
		idx := mustIndex(blockSizeNames, row[1], "block size")
		match := cdfPattern.FindStringSubmatch(row[2])
		if len(match) != 3 {
			fatalf("use_filter_intra for %s: cdf not found", row[1])
		}
		values[idx] = parseCDFValues(match[2])
	}

	fmt.Fprintf(buf, "var generatedUseFilterIntraCDF = [%d][2]uint16{\n", len(blockSizeNames))
	for _, vals := range values {
		fmt.Fprintf(buf, "%s,\n", formatUint16Array(vals, 2))
	}
	fmt.Fprintln(buf, "}")
	fmt.Fprintln(buf)
}

func writeUVModeCDF(buf *bytes.Buffer, cdfText string) {
	block := extractSection(cdfText, ".uv_mode = {", ".angle_delta = {")
	matches := cdfPattern.FindAllStringSubmatch(block, -1)
	if len(matches) != 26 {
		fatalf("uv_mode cdf count = %d, want 26", len(matches))
	}
	fmt.Fprintln(buf, "var generatedUVModeCDF = [2][13][14]uint16{")
	idx := 0
	for allowed := 0; allowed < 2; allowed++ {
		fmt.Fprintln(buf, "{")
		for mode := 0; mode < 13; mode++ {
			vals := parseCDFValues(matches[idx][2])
			idx++
			fmt.Fprintf(buf, "%s,\n", formatUint16Array(vals, 14))
		}
		fmt.Fprintln(buf, "},")
	}
	fmt.Fprintln(buf, "}")
	fmt.Fprintln(buf)
}

func write3DCDFArray(buf *bytes.Buffer, cdfText, marker, nextMarker, name string, d1, d2, size int) {
	block := extractSection(cdfText, marker, nextMarker)
	matches := cdfPattern.FindAllStringSubmatch(block, -1)
	if len(matches) != d1*d2 {
		fatalf("%s cdf count = %d, want %d", name, len(matches), d1*d2)
	}
	fmt.Fprintf(buf, "var %s = [%d][%d][%d]uint16{\n", name, d1, d2, size)
	idx := 0
	for i := 0; i < d1; i++ {
		fmt.Fprintln(buf, "{")
		for j := 0; j < d2; j++ {
			vals := parseCDFValues(matches[idx][2])
			idx++
			fmt.Fprintf(buf, "%s,\n", formatUint16Array(vals, size))
		}
		fmt.Fprintln(buf, "},")
	}
	fmt.Fprintln(buf, "}")
	fmt.Fprintln(buf)
}

func write4DCDFArray(buf *bytes.Buffer, cdfText, marker, nextMarker, name string, d1, d2, d3, size int) {
	block := extractSection(cdfText, marker, nextMarker)
	matches := cdfPattern.FindAllStringSubmatch(block, -1)
	if len(matches) != d1*d2*d3 {
		fatalf("%s cdf count = %d, want %d", name, len(matches), d1*d2*d3)
	}
	fmt.Fprintf(buf, "var %s = [%d][%d][%d][%d]uint16{\n", name, d1, d2, d3, size)
	idx := 0
	for i := 0; i < d1; i++ {
		fmt.Fprintln(buf, "{")
		for j := 0; j < d2; j++ {
			fmt.Fprintln(buf, "{")
			for k := 0; k < d3; k++ {
				vals := parseCDFValues(matches[idx][2])
				idx++
				fmt.Fprintf(buf, "%s,\n", formatUint16Array(vals, size))
			}
			fmt.Fprintln(buf, "},")
		}
		fmt.Fprintln(buf, "},")
	}
	fmt.Fprintln(buf, "}")
	fmt.Fprintln(buf)
}

func writeKFYModeCDF(buf *bytes.Buffer, cdfText string) {
	block := extractBlock(cdfText, ".kfym = {")
	matches := cdfPattern.FindAllStringSubmatch(block, -1)
	if len(matches) != 25 {
		fatalf("kfym cdf count = %d, want 25", len(matches))
	}
	fmt.Fprintln(buf, "var generatedKFYModeCDF = [5][5][13]uint16{")
	idx := 0
	for top := 0; top < 5; top++ {
		fmt.Fprintln(buf, "{")
		for left := 0; left < 5; left++ {
			vals := parseCDFValues(matches[idx][2])
			idx++
			fmt.Fprintf(buf, "%s,\n", formatUint16Array(vals, 13))
		}
		fmt.Fprintln(buf, "},")
	}
	fmt.Fprintln(buf, "}")
	fmt.Fprintln(buf)
}

func writeCoefCDFTables(buf *bytes.Buffer, cdfText string) {
	qcatBlocks := extractIndexedBlocks(cdfText, "static const CdfCoefContext default_coef_cdf[4] = {", 4)
	writeQCat3DCDFArray(buf, qcatBlocks, ".skip = {", ".eob_bin_16 = {", "generatedCoefSkipCDF", 5, 13, 2)
	writeQCat3DCDFArray(buf, qcatBlocks, ".eob_bin_16 = {", ".eob_bin_32 = {", "generatedEOBBin16CDF", 2, 2, 5)
	writeQCat3DCDFArray(buf, qcatBlocks, ".eob_bin_32 = {", ".eob_bin_64 = {", "generatedEOBBin32CDF", 2, 2, 6)
	writeQCat3DCDFArray(buf, qcatBlocks, ".eob_bin_64 = {", ".eob_bin_128 = {", "generatedEOBBin64CDF", 2, 2, 7)
	writeQCat3DCDFArray(buf, qcatBlocks, ".eob_bin_128 = {", ".eob_bin_256 = {", "generatedEOBBin128CDF", 2, 2, 8)
	writeQCat3DCDFArray(buf, qcatBlocks, ".eob_bin_256 = {", ".eob_bin_512 = {", "generatedEOBBin256CDF", 2, 2, 9)
	writeQCat2DCDFArray(buf, qcatBlocks, ".eob_bin_512 = {", ".eob_bin_1024 = {", "generatedEOBBin512CDF", 2, 10)
	writeQCat2DCDFArray(buf, qcatBlocks, ".eob_bin_1024 = {", ".eob_hi_bit = {", "generatedEOBBin1024CDF", 2, 11)
	writeQCat4DCDFArray(buf, qcatBlocks, ".eob_hi_bit = {", ".eob_base_tok = {", "generatedEOBHiBitCDF", 5, 2, 9, 2)
	writeQCat4DCDFArray(buf, qcatBlocks, ".eob_base_tok = {", ".base_tok = {", "generatedEOBBaseTokCDF", 5, 2, 4, 3)
	writeQCat4DCDFArray(buf, qcatBlocks, ".base_tok = {", ".dc_sign = {", "generatedBaseTokCDF", 5, 2, 41, 4)
	writeQCat3DCDFArray(buf, qcatBlocks, ".dc_sign = {", ".br_tok = {", "generatedDCSignCDF", 2, 3, 2)
	writeQCat4DCDFArray(buf, qcatBlocks, ".br_tok = {", "", "generatedBRTokCDF", 4, 2, 21, 4)
}

func writeMVCDFTables(buf *bytes.Buffer, cdfText string) {
	block := extractBlock(cdfText, ".mv = {")
	comp := extractBlock(block, ".comp = {")

	writeSingleCDFFromBlock(buf, comp, ".classes = {", "generatedMVClassesCDF", 11)
	writeSingleCDFFromBlock(buf, comp, ".class0 = {", "generatedMVClass0CDF", 2)
	write1DCDFArrayFromBlock(buf, comp, ".classN = {", ".class0_fp = {", "generatedMVClassNCDF", 10, 2)
	write1DCDFArrayFromBlock(buf, comp, ".class0_fp = {", ".classN_fp = {", "generatedMVClass0FPCDF", 2, 4)
	writeSingleCDFFromBlock(buf, comp, ".classN_fp = {", "generatedMVClassNFPCDF", 4)
	writeSingleCDFFromBlock(buf, comp, ".class0_hp = {", "generatedMVClass0HPCDF", 2)
	writeSingleCDFFromBlock(buf, comp, ".classN_hp = {", "generatedMVClassNHPCDF", 2)
	writeSingleCDFFromBlock(buf, comp, ".sign = {", "generatedMVSignCDF", 2)
	writeSingleCDFFromBlock(buf, block, ".joint = {", "generatedMVJointCDF", 4)
}

func writeSingleCDFFromBlock(buf *bytes.Buffer, block, marker, name string, size int) {
	field := extractBlock(block, marker)
	match := cdfPattern.FindStringSubmatch(field)
	if len(match) != 3 {
		fatalf("%s: cdf not found", name)
	}
	vals := parseCDFValues(match[2])
	fmt.Fprintf(buf, "var %s = %s\n\n", name, formatUint16Array(vals, size))
}

func write1DCDFArrayFromBlock(buf *bytes.Buffer, block, marker, nextMarker, name string, rows, size int) {
	field := extractSection(block, marker, nextMarker)
	matches := cdfPattern.FindAllStringSubmatch(field, -1)
	if len(matches) != rows {
		fatalf("%s cdf count = %d, want %d", name, len(matches), rows)
	}
	fmt.Fprintf(buf, "var %s = [%d][%d]uint16{\n", name, rows, size)
	for _, m := range matches {
		vals := parseCDFValues(m[2])
		fmt.Fprintf(buf, "%s,\n", formatUint16Array(vals, size))
	}
	fmt.Fprintln(buf, "}")
	fmt.Fprintln(buf)
}

func writeQCat2DCDFArray(buf *bytes.Buffer, qcatBlocks []string, marker, nextMarker, name string, d1, size int) {
	fmt.Fprintf(buf, "var %s = [%d][%d][%d]uint16{\n", name, len(qcatBlocks), d1, size)
	for _, qcat := range qcatBlocks {
		field := extractField(qcat, marker, nextMarker)
		matches := cdfPattern.FindAllStringSubmatch(field, -1)
		if len(matches) != d1 {
			fatalf("%s cdf count = %d, want %d", name, len(matches), d1)
		}
		fmt.Fprintln(buf, "{")
		for _, m := range matches {
			vals := parseCDFValues(m[2])
			fmt.Fprintf(buf, "%s,\n", formatUint16Array(vals, size))
		}
		fmt.Fprintln(buf, "},")
	}
	fmt.Fprintln(buf, "}")
	fmt.Fprintln(buf)
}

func writeQCat3DCDFArray(buf *bytes.Buffer, qcatBlocks []string, marker, nextMarker, name string, d1, d2, size int) {
	fmt.Fprintf(buf, "var %s = [%d][%d][%d][%d]uint16{\n", name, len(qcatBlocks), d1, d2, size)
	for _, qcat := range qcatBlocks {
		field := extractField(qcat, marker, nextMarker)
		matches := cdfPattern.FindAllStringSubmatch(field, -1)
		if len(matches) != d1*d2 {
			fatalf("%s cdf count = %d, want %d", name, len(matches), d1*d2)
		}
		fmt.Fprintln(buf, "{")
		idx := 0
		for i := 0; i < d1; i++ {
			fmt.Fprintln(buf, "{")
			for j := 0; j < d2; j++ {
				vals := parseCDFValues(matches[idx][2])
				idx++
				fmt.Fprintf(buf, "%s,\n", formatUint16Array(vals, size))
			}
			fmt.Fprintln(buf, "},")
		}
		fmt.Fprintln(buf, "},")
	}
	fmt.Fprintln(buf, "}")
	fmt.Fprintln(buf)
}

func writeQCat4DCDFArray(buf *bytes.Buffer, qcatBlocks []string, marker, nextMarker, name string, d1, d2, d3, size int) {
	fmt.Fprintf(buf, "var %s = [%d][%d][%d][%d][%d]uint16{\n", name, len(qcatBlocks), d1, d2, d3, size)
	for _, qcat := range qcatBlocks {
		field := extractField(qcat, marker, nextMarker)
		matches := cdfPattern.FindAllStringSubmatch(field, -1)
		if len(matches) != d1*d2*d3 {
			fatalf("%s cdf count = %d, want %d", name, len(matches), d1*d2*d3)
		}
		fmt.Fprintln(buf, "{")
		idx := 0
		for i := 0; i < d1; i++ {
			fmt.Fprintln(buf, "{")
			for j := 0; j < d2; j++ {
				fmt.Fprintln(buf, "{")
				for k := 0; k < d3; k++ {
					vals := parseCDFValues(matches[idx][2])
					idx++
					fmt.Fprintf(buf, "%s,\n", formatUint16Array(vals, size))
				}
				fmt.Fprintln(buf, "},")
			}
			fmt.Fprintln(buf, "},")
		}
		fmt.Fprintln(buf, "},")
	}
	fmt.Fprintln(buf, "}")
	fmt.Fprintln(buf)
}

func writeScalarTable(buf *bytes.Buffer, tablesText, cName string, names []string, goName string) {
	block := extractBlock(tablesText, cName)
	values := make([]string, len(names))
	for _, m := range designatedScalar.FindAllStringSubmatch(block, -1) {
		idx := mustIndex(names, m[1], cName)
		values[idx] = translateSymbol(m[2])
	}
	fmt.Fprintf(buf, "var %s = [%d]uint8{", goName, len(names))
	for i, v := range values {
		if i > 0 {
			fmt.Fprint(buf, ", ")
		}
		if v == "" {
			v = "0"
		}
		fmt.Fprint(buf, v)
	}
	fmt.Fprintln(buf, "}")
	fmt.Fprintln(buf)
}

func writeFlatScalarListTable(buf *bytes.Buffer, tablesText, cName string, size int, goName string) {
	block := extractBlock(tablesText, cName)
	start := strings.Index(block, "{")
	end := strings.LastIndex(block, "}")
	if start < 0 || end < 0 || end <= start {
		fatalf("%s: malformed scalar list", cName)
	}
	content := regexp.MustCompile(`(?s)/\*.*?\*/`).ReplaceAllString(block[start+1:end], "")
	parts := splitCSV(content)
	if len(parts) != size {
		fatalf("%s: list size = %d, want %d", cName, len(parts), size)
	}
	fmt.Fprintf(buf, "var %s = [%d]uint8{", goName, size)
	for i, part := range parts {
		if i > 0 {
			fmt.Fprint(buf, ", ")
		}
		fmt.Fprint(buf, translateSymbol(part))
	}
	fmt.Fprintln(buf, "}")
	fmt.Fprintln(buf)
}

func writeDequantTable(buf *bytes.Buffer, dequantText string) {
	block := extractBlock(dequantText, "const uint16_t dav1d_dq_tbl[3][QINDEX_RANGE][2] = {")
	re := regexp.MustCompile(`\{\s*(\d+)\s*,\s*(\d+)\s*,?\s*\}`)
	matches := re.FindAllStringSubmatch(block, -1)
	if len(matches) != 3*256 {
		fatalf("dequant entry count = %d, want %d", len(matches), 3*256)
	}
	fmt.Fprintln(buf, "var generatedDQTable = [3][256][2]uint16{")
	idx := 0
	for plane := 0; plane < 3; plane++ {
		fmt.Fprintln(buf, "{")
		for q := 0; q < 256; q++ {
			fmt.Fprintf(buf, "{%s, %s},\n", matches[idx][1], matches[idx][2])
			idx++
		}
		fmt.Fprintln(buf, "},")
	}
	fmt.Fprintln(buf, "}")
	fmt.Fprintln(buf)
}

func writeScanTables(buf *bytes.Buffer, scanText string) {
	matches := scanArrayPattern.FindAllStringSubmatch(scanText, -1)
	if len(matches) == 0 {
		fatalf("scan arrays not found")
	}

	unique := map[string][]string{
		"scan_4x4":   nil,
		"scan_8x8":   nil,
		"scan_16x16": nil,
		"scan_32x32": nil,
		"scan_4x8":   nil,
		"scan_8x4":   nil,
		"scan_8x16":  nil,
		"scan_16x8":  nil,
		"scan_16x32": nil,
		"scan_32x16": nil,
		"scan_4x16":  nil,
		"scan_16x4":  nil,
		"scan_8x32":  nil,
		"scan_32x8":  nil,
	}
	for _, m := range matches {
		if _, ok := unique[m[1]]; !ok {
			continue
		}
		unique[m[1]] = splitCSV(m[2])
	}

	for _, name := range []string{
		"scan_4x4", "scan_8x8", "scan_16x16", "scan_32x32",
		"scan_4x8", "scan_8x4", "scan_8x16", "scan_16x8",
		"scan_16x32", "scan_32x16", "scan_4x16", "scan_16x4",
		"scan_8x32", "scan_32x8",
	} {
		vals := unique[name]
		if vals == nil {
			fatalf("scan table %s not found", name)
		}
		fmt.Fprintf(buf, "var %s = []uint16{", goScanName(name))
		for i, v := range vals {
			if i > 0 {
				fmt.Fprint(buf, ", ")
			}
			fmt.Fprint(buf, strings.TrimSpace(v))
		}
		fmt.Fprintln(buf, "}")
		fmt.Fprintln(buf)
	}

	fmt.Fprintf(buf, "var generatedScans = [%d][]uint16{\n", len(rectTxfmSizeNames))
	for _, txName := range rectTxfmSizeNames {
		fmt.Fprintf(buf, "%s,\n", goScanName(scanNameForTX[txName]))
	}
	fmt.Fprintln(buf, "}")
	fmt.Fprintln(buf)
}

func goScanName(name string) string {
	return "generated" + strings.ReplaceAll(strings.Title(strings.ReplaceAll(name, "_", " ")), " ", "")
}

func writeRowTable(buf *bytes.Buffer, tablesText, cName string, names []string, rowLen int, goName string) {
	block := extractBlock(tablesText, cName)
	rows := make([][]string, len(names))
	for _, m := range designatedRow.FindAllStringSubmatch(block, -1) {
		idx := mustIndex(names, m[1], cName)
		parts := splitCSV(m[2])
		row := make([]string, rowLen)
		for i := 0; i < rowLen && i < len(parts); i++ {
			row[i] = translateSymbol(parts[i])
		}
		rows[idx] = row
	}

	fmt.Fprintf(buf, "var %s = [%d][%d]uint8{\n", goName, len(names), rowLen)
	for _, row := range rows {
		fmt.Fprint(buf, "{")
		for i := 0; i < rowLen; i++ {
			if i > 0 {
				fmt.Fprint(buf, ", ")
			}
			v := "0"
			if i < len(row) && row[i] != "" {
				v = row[i]
			}
			fmt.Fprint(buf, v)
		}
		fmt.Fprintln(buf, "},")
	}
	fmt.Fprintln(buf, "}")
	fmt.Fprintln(buf)
}

func extractSection(text, marker, nextMarker string) string {
	start := strings.Index(text, marker)
	if start < 0 {
		fatalf("marker %q not found", marker)
	}
	start += len(marker)
	end := strings.Index(text[start:], nextMarker)
	if end < 0 {
		fatalf("next marker %q not found after %q", nextMarker, marker)
	}
	return text[start : start+end]
}

func extractBlock(text, marker string) string {
	start := strings.Index(text, marker)
	if start < 0 {
		fatalf("marker %q not found", marker)
	}
	start = strings.Index(text[start:], "{") + start
	if start < 0 {
		fatalf("open brace not found after %q", marker)
	}
	depth := 0
	for i := start; i < len(text); i++ {
		switch text[i] {
		case '{':
			depth++
		case '}':
			depth--
			if depth == 0 {
				return text[start : i+1]
			}
		}
	}
	fatalf("unclosed block for %q", marker)
	return ""
}

func extractField(text, marker, nextMarker string) string {
	if nextMarker == "" {
		return extractBlock(text, marker)
	}
	return extractSection(text, marker, nextMarker)
}

func extractIndexedBlocks(text, marker string, count int) []string {
	block := extractBlock(text, marker)
	re := regexp.MustCompile(`\[(\d+)\]\s*=\s*\{`)
	matches := re.FindAllStringSubmatchIndex(block, -1)
	if len(matches) != count {
		fatalf("%s block count = %d, want %d", marker, len(matches), count)
	}
	blocks := make([]string, count)
	for _, m := range matches {
		idx := mustAtoi(block[m[2]:m[3]])
		if idx < 0 || idx >= count {
			fatalf("%s index out of range: %d", marker, idx)
		}
		open := m[1] - 1
		depth := 0
		end := -1
		for i := open; i < len(block); i++ {
			switch block[i] {
			case '{':
				depth++
			case '}':
				depth--
				if depth == 0 {
					end = i + 1
				}
			}
			if end >= 0 {
				break
			}
		}
		if end < 0 {
			fatalf("%s index %d: unclosed block", marker, idx)
		}
		blocks[idx] = block[open:end]
	}
	return blocks
}

func parseCDFValues(list string) []uint16 {
	parts := splitCSV(list)
	out := make([]uint16, 0, len(parts))
	for _, part := range parts {
		v := mustAtoi(part)
		out = append(out, uint16(32768-v))
	}
	return out
}

func formatUint16Array(vals []uint16, size int) string {
	var parts []string
	for _, v := range vals {
		parts = append(parts, strconv.Itoa(int(v)))
	}
	for len(parts) < size {
		parts = append(parts, "0")
	}
	return fmt.Sprintf("[%d]uint16{%s}", size, strings.Join(parts, ", "))
}

func splitCSV(s string) []string {
	raw := strings.Split(s, ",")
	out := make([]string, 0, len(raw))
	for _, part := range raw {
		part = strings.TrimSpace(strings.Trim(part, "{}"))
		if part == "" {
			continue
		}
		out = append(out, part)
	}
	return out
}

func translateSymbol(s string) string {
	s = strings.TrimSpace(s)
	if n, err := strconv.Atoi(s); err == nil {
		return strconv.Itoa(n)
	}
	if idx, ok := txSizeIndex[s]; ok {
		return strconv.Itoa(idx)
	}
	if idx, ok := intraModeIndex[s]; ok {
		return strconv.Itoa(idx)
	}
	fatalf("unmapped symbol %q", s)
	return ""
}

func mustIndex(list []string, name, kind string) int {
	for i, v := range list {
		if v == name {
			return i
		}
	}
	fatalf("%s entry %q not found", kind, name)
	return -1
}

func mustAtoi(s string) int {
	v, err := strconv.Atoi(strings.TrimSpace(s))
	if err != nil {
		fatalf("parse int %q: %v", s, err)
	}
	return v
}

func readFile(path string) string {
	b, err := os.ReadFile(path)
	if err != nil {
		fatalf("read %s: %v", path, err)
	}
	return string(b)
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}

var blockSizeNames = []string{
	"BS_128x128", "BS_128x64", "BS_64x128", "BS_64x64", "BS_64x32", "BS_64x16",
	"BS_32x64", "BS_32x32", "BS_32x16", "BS_32x8", "BS_16x64", "BS_16x32",
	"BS_16x16", "BS_16x8", "BS_16x4", "BS_8x32", "BS_8x16", "BS_8x8",
	"BS_8x4", "BS_4x16", "BS_4x8", "BS_4x4",
}

var intraModeNames = []string{
	"DC_PRED", "VERT_PRED", "HOR_PRED", "DIAG_DOWN_LEFT_PRED", "DIAG_DOWN_RIGHT_PRED",
	"VERT_RIGHT_PRED", "HOR_DOWN_PRED", "HOR_UP_PRED", "VERT_LEFT_PRED", "SMOOTH_PRED",
	"SMOOTH_V_PRED", "SMOOTH_H_PRED", "PAETH_PRED", "CFL_PRED",
}

var intraLumaModeNames = []string{
	"DC_PRED", "VERT_PRED", "HOR_PRED", "DIAG_DOWN_LEFT_PRED", "DIAG_DOWN_RIGHT_PRED",
	"VERT_RIGHT_PRED", "HOR_DOWN_PRED", "HOR_UP_PRED", "VERT_LEFT_PRED", "SMOOTH_PRED",
	"SMOOTH_V_PRED", "SMOOTH_H_PRED", "PAETH_PRED",
}

var uvModeNames = intraModeNames

var rectTxfmSizeNames = []string{
	"TX_4X4", "TX_8X8", "TX_16X16", "TX_32X32", "TX_64X64",
	"RTX_4X8", "RTX_8X4", "RTX_8X16", "RTX_16X8", "RTX_16X32",
	"RTX_32X16", "RTX_32X64", "RTX_64X32", "RTX_4X16", "RTX_16X4",
	"RTX_8X32", "RTX_32X8", "RTX_16X64", "RTX_64X16",
}

var scanNameForTX = map[string]string{
	"TX_4X4":    "scan_4x4",
	"TX_8X8":    "scan_8x8",
	"TX_16X16":  "scan_16x16",
	"TX_32X32":  "scan_32x32",
	"TX_64X64":  "scan_32x32",
	"RTX_4X8":   "scan_4x8",
	"RTX_8X4":   "scan_8x4",
	"RTX_8X16":  "scan_8x16",
	"RTX_16X8":  "scan_16x8",
	"RTX_16X32": "scan_16x32",
	"RTX_32X16": "scan_32x16",
	"RTX_32X64": "scan_32x32",
	"RTX_64X32": "scan_32x32",
	"RTX_4X16":  "scan_4x16",
	"RTX_16X4":  "scan_16x4",
	"RTX_8X32":  "scan_8x32",
	"RTX_32X8":  "scan_32x8",
	"RTX_16X64": "scan_16x32",
	"RTX_64X16": "scan_32x16",
}

var txSizeIndex = map[string]int{
	"TX_4X4": 0, "TX_8X8": 1, "TX_16X16": 2, "TX_32X32": 3, "TX_64X64": 4,
	"RTX_4X8": 5, "RTX_8X4": 6, "RTX_8X16": 7, "RTX_16X8": 8, "RTX_16X32": 9,
	"RTX_32X16": 10, "RTX_32X64": 11, "RTX_64X32": 12, "RTX_4X16": 13,
	"RTX_16X4": 14, "RTX_8X32": 15, "RTX_32X8": 16, "RTX_16X64": 17, "RTX_64X16": 18,
	"DCT_DCT": 0, "ADST_DCT": 1, "DCT_ADST": 2, "ADST_ADST": 3, "FLIPADST_DCT": 4,
	"DCT_FLIPADST": 5, "FLIPADST_FLIPADST": 6, "ADST_FLIPADST": 7, "FLIPADST_ADST": 8,
	"IDTX": 9, "V_DCT": 10, "H_DCT": 11, "V_ADST": 12, "H_ADST": 13,
	"V_FLIPADST": 14, "H_FLIPADST": 15,
}

var intraModeIndex = map[string]int{
	"DC_PRED": 0, "VERT_PRED": 1, "HOR_PRED": 2, "DIAG_DOWN_LEFT_PRED": 3, "DIAG_DOWN_RIGHT_PRED": 4,
	"VERT_RIGHT_PRED": 5, "HOR_DOWN_PRED": 6, "HOR_UP_PRED": 7, "VERT_LEFT_PRED": 8,
	"SMOOTH_PRED": 9, "SMOOTH_V_PRED": 10, "SMOOTH_H_PRED": 11, "PAETH_PRED": 12,
	"CFL_PRED": 13,
}
